name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Update to write permissions if you need to publish a package
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Ensure this matches your local environment

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clear npm cache (if needed)
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Check directory structure
        run: |
          echo "Contents of src:"
          ls -R src

      - name: Build
        run: npm run build --verbose # Build your project

      - name: Publish package
        run: npx jsr publish --allow-dirty
